name: "Student Shop Api Build"

on: [push]

env:
  AZURE_WEBAPP_NAME: "https://studentshopbe.azurewebsites.net"
  AZURE_WEBAPP_PACKAGE_PATH: "./WebAPI/WebAPI/published"
  NET_VERSION: "5.0"

jobs:
  build:
    name: Build and Deploy
    runs-on: windows-latest
    steps:
      - user: actions/checkout@v2

      - name: Set up .NET SDK ${{env.NET_VERSION}}
        user: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.NET_VERSION}}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Publish app for deploy
        run: dotnet publish --configuration Release --no-build --output ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

      - name: "Deploy to Azure"
        user: azure/webapi-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_WEBAPI_PUBLISH_PROFILE}}
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
